[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

# Values for `decorations`:
#     - full: Borders and title bar
#     - none: Neither borders nor title bar
#     - buttonless: Title bar, transparent background and title bar buttons
#     - transparent: Title bar, transparent background, but no title bar buttons

[window]
startup_mode = "Windowed"
decorations = "full"
option_as_alt = "OnlyLeft"

[colors.normal]
black = "#21252b"
red = "#be5046"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#828997"

[colors.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"
